### ISSUE TITLE
KLdiv in PPOModel

### ISSUE THREAD

**Issue by GolovanovSrg** [reinforceio/tensorforce#107]
https://github.com/reinforceio/tensorforce/blob/4538be55121ea90b744046c883475582183c2a93/tensorforce/models/ppo_model.py#L97
I think that need swap distribution and prev_distribution. KL(p || q) != KL(q || p). In TRPO theorem we need small KL(old policy || new policy).

**Comment by AlexKuhnle** [comment]
Thanks for reporting! However, I think that this is not actually an issue, since the KL divergence in PPO is only used for diagnostic logging. In TRPO, the same is done, but the KL divergence which is used for the actual update calculation is the other way round ([update](https://github.com/reinforceio/tensorforce/blob/4538be55121ea90b744046c883475582183c2a93/tensorforce/models/trpo_model.py#L100) vs [diagnostics](https://github.com/reinforceio/tensorforce/blob/4538be55121ea90b744046c883475582183c2a93/tensorforce/models/trpo_model.py#L109)). Would you say that it would nevertheless make sense to swap the arguments, i.e. report the distance of the old to the new distribution instead of the new to the old?

**Comment by GolovanovSrg** [comment]
I think that even for diagnostic must use KL(old policy || new policy).

**Comment by AlexKuhnle** [comment]
Okay, done.
