### ISSUE TITLE
Configuration refactoring - thoughts and suggestions welcome!

### ISSUE THREAD

**Issue by trickmeyer** [reinforceio/tensorforce#132]
Configuration has been a topic of discussion for quite some time now, so I thought it'd be a good idea to get all those thoughts in one place and hopefully solicit some user thoughts as well.  

From my understanding, the current purposes of configs are:

1. make it easy for people to get up and running
2. get all parameters in one place for ease of setting up experiments and making them interpretable
3. keep signatures simple, which makes it easy to create arbitrary things from one big blob

The current issues I'm having with configs are:

1. they are somewhere between a dictionary and a blob-object, which makes them confusing
2. they aren't serializable, so I have to create config wrappers around Configurations.  Eww.
3. defaults and unused parameters make it challenging to know what's really being used.

My personal opinion is that we can keep benefits (1) and (2) above and get rid of all three issues all in exchange for the small sacrifice of benefit (3).  In fact, I don't know how much of a benefit (3) is, as it obfuscates the true parameters of all objects in the codebase.  

I would propose doing so by putting the burden of the parameter creation and passing into the constructors of objects onto the user.  Any intermediate user will have experience creating parameter/config generation wrappers. Less experienced users who want to get up and running quickly can still use the same JSON objects you've already written with something like this when actually creating the objects downstream:

`SomeObject(config_dict['some_key'], config_dict['another_key'])`

Users who want to create defaults can do this:

`SomeObject(config_dict.get('some_key', default_value), config_dict.get('another_key', another_default_value))`

Which to me is a much more clear way of going about defaults.  

The side benefit of all of this is that you aren't stuck supporting configurations for users.  Configuration and deployment are two challenging parts of any project, and I personally would prefer everyone's time spent on RL, not trying to solve a fundamental CS issue (configuration!) that in the end is always problem-specific, and no matter how hard we try, never suits everyone's needs.

**Comment by AlexKuhnle** [comment]
First, a question for clarification: Do you mean that the parameters are passed as *'proper'* arguments, i.e. for instance `VPGAgent(learning_rate=..., discount=..., gae_lambda=..., etc)` instead of `VPGAgent(config)`?

**Comment by trickmeyer** [comment]
@AlexKuhnle after my experiences so far, that would be my preference.  I know that won't be universal.

**Comment by AlexKuhnle** [comment]
Moreover, here some ideas or partially already implemented things in my local version:
- We currently transform every sub-dict of a `Configuration` into another `Configuration`, something which by now turns out to be quite bad and counter-intuitive. Here I would suggest taking the `Configuration` as one-layer collection of parameters instead (which can be dictionaries).
- For more 'historical' reasons we have singled out some parameters as top-level, where really they should be sub-parameters. This includes `leaning_rate` as sub-parameter for `optimizer` as well as `memory_capacity` as part of `memory`, and some others. Proposal is obviously to move them where they belong.
- We currently have `default_config` dicts defined in all the classes where a parameter is used. With more recent work on the long-promised optimizers, I'm more and more inclined to, first, potentially break the symmetry between models and agents and, second, move all default values into the final algorithm-specific `Agent` implementation, of which there could be many (original DQN, double DQN, prioritized DQN, specific DQN used in whatever paper, etc)...
Particularly the last point only leaves the question whether the parameters should be moved through as one object or as many arguments. In particular, there are some arguments, most notably `states` and `actions`, which are somewhat different from the usual hyperparameters, hence for them I would be inclined to single them out.

**Comment by trickmeyer** [comment]
@AlexKuhnle i'd like to add `network` to your last point of `states` and `actions` being different from usual hyperparameters.

**Comment by AlexKuhnle** [comment]
Good point, and yet another slightly different *'hyperparameter'*. What I'm more or less happy with is the way we have one uniform interface to either use pre-defined (say, `optimizer='adam'`) or custom functions/classes by passing either the function or the *'python path'* (say, `optimizer=my_module.my_optimizer.Optimizer`). In fact, one could do something similar for the network (or, it is kind of done, but only kind of...).

**Comment by trickmeyer** [comment]
@AlexKuhnle I agree the uniform interface is nice.  Could we achieve that while also creating the instances on the user-side with something like this?

`Optimizer = tensorforce.defaults.AdamOptimizer()`

or (custom)

`Optimizer = my_module.my_optimizer.Optimizer(*args, **kwargs)`

and then calling `Experiment` (based on my above) or `Runner` (current) with `Runner(my_agent, my_network, ..., my_optimizer)`.

**Comment by AlexKuhnle** [comment]
Hmm, I guess it could be done, but is it a problem if you have to pass the callable? My thought is that you can always create a wrapper lambda expression, like `lambda x: my_module.my_optimizer.Optimizer(x, y, z)`. But anyway, should be easily doable by modifying the util functions used in these cases.

**Comment by tms1337** [comment]
When I just started using (tensorforce) it was really a bit painful to get to the bottom of the configuration so I do think this really is one of the main points we should work on. 

I thought about improving documentation so people do not bump into the same issues as I did, but if the configuration itself will be updated, I would rather help on that then, so please update if you can use some help.

**Comment by AlexKuhnle** [comment]
The new version will handle configs somewhat differently, and is inspired by the discussion here, hence let's continue this discussion in a week or so... It will of course never be perfect, but it's an attempt to get rid of some obvious problems that repeatedly came up.

**Comment by AlexKuhnle** [comment]
The new version still uses a `Configuration` object, which now merely acts as a 'container' for all hyperparameters. State/action/network specifications are separate arguments. Default values are only specified in the final `Agent` sub-class and only the relevant ones for this implementation, like in [VPGAgent](https://github.com/reinforceio/tensorforce/blob/dev/tensorforce/agents/vpg_agent.py). It's possible to pass initialized instances, or alternatively pass something like `{'type': 'my_module.MyOptimizer', 'arg1': XXX, 'arg2': YYY, ...}` to achieve the same.

Is there anything else you think is clearly not ideal?

**Comment by trickmeyer** [comment]
When I asked @michaelschaarschmidt who the core audience was, he said it was people who would be capable of working as a ML engineer.  Given that, I would personally ditch configs altogether and put the burden of creating initialized instances of the core components of a run on the user.  You can still have "off the shelf" examples, they just wouldn't exist via configs.

It seems like the `Configuration` object just creates overhead/maintenance for the team, and creates mysterious issues for the user.

These are personal opinions, and although they are strong, they are weakly-held.  I support whatever you and the team decides.

Should you proceed with the Config route, I would request a very easy-to-use method where I can get a fully-correct version of the actual config that was used for the run, after any possible mutations downstream from the point I pass it in.  I'm sure I'm not alone in wanting to verify what my run is using is actually what I think it is.

**Comment by trickmeyer** [comment]
But, to answer your question about things that are *clearly* not ideal: nothing right now.  This would be require another refactoring, and I know now isn't the time.

**Comment by AlexKuhnle** [comment]
I definitely like the alternative without any `Configuration` object as well. The only annoying 'issue' with that would be that there might be 20+ arguments to pass through quite a few constructors (particularly all the options required in the 'last' object of the constructor chain, the `Model`), while the upside would be that everything is very explicit. The former could probably be improved by introducing container dicts for `logging` and `tf_session` or so, similar to values like `optimizer`.

To be clear, this aspect of the `Configuration` object acting as a 'container' is the only difference to getting rid of it entirely, since all `default_config` objects and changing values doesn't happen anymore, so the only place where the config object changes is in the `Agent` subclasses like VPGAgent. So removing the `Configuration` object really is no big deal anymore. The more I think about it, I agree that it might be best to just finally get rid of it entirely (e.g. more straightforward documentation of parameters as constructor arguments). I'll ask the others what they think...

**Comment by tms1337** [comment]
From the user perspective I agree with removing the Configuration object. I recently started using tensorforce and it would be much easier if all arguments were available at constructors, instead I had to read docs, library code and ask on Gitter. Just my personal experience, perhaps it does not generalize to others.

**Comment by trickmeyer** [comment]
@AlexKuhnle I know better documentation is on the roadmap for the project as well, and that's a lot easier and better supported via parameters in constructors than it is in comments in configuration files or in-line in examples.

Long constructors can be annoying, but they are also a subtle nudge for people to take more time considering what they're doing and learning about what factors really influence their experiments.

**Comment by AlexKuhnle** [comment]
Totally agree, I'm convinced. :-)

**Comment by trickmeyer** [comment]
Yes!  Well - let me know if you want me to change the title of this issue at any point to "Remove Configuration - Pass Parameters in Constructors" or something like that.

**Comment by AlexKuhnle** [comment]
Nah, that's alright, we'll just try to close it soon...

**Comment by AlexKuhnle** [comment]
Just to let you know: We decided that we will first try to merge the dev branch with master asap (probably today), and then probably integrate this change as a minor version update in the next weeks.

**Comment by AlexKuhnle** [comment]
This will hopefully be finished this weekend by @michaelschaarschmidt, just to let you know @trickmeyer.

**Comment by michaelschaarschmidt** [comment]
Configuration object is gone and I hope everyone is (largely) happy with this so we can avoid breaking changes for a while
