### ISSUE TITLE
Batch actions?

### ISSUE THREAD

**Issue by wangell** [reinforceio/tensorforce#137]
Is there a way to generate actions in a batch to take full advantage of the GPU (so using the same model parameters but generate actions for multiple states)?  Right now it seems you can only operate on one state/action at a time.

**Comment by michaelschaarschmidt** [comment]
This is a sensible feature we could add soon - the next few weeks we are busy refactoring to enable new optimizers though

**Comment by wangell** [comment]
I'll try my hand at this as well, and submit a patch...  It looks like I can just add a new get_actions functions to the model base class that constructs a feed_dict with multiple states? Not sure how to handle the internals yet.  Any pointers?

**Comment by michaelschaarschmidt** [comment]
In the case of no internals, this should be easy and an empty list should suffice. The LSTM requires alternating actions and observes though..

**Comment by AlexKuhnle** [comment]
I guess you would have to just add list-versions of the `Agent.current_XXX` attributes. One would then still assume a sequence of act-observe-act-... with lists of always the same length. However, how this is handled in `BatchAgent` or `MemoryAgent` to not mix up the temporal sequence of timesteps is a more difficult question (if the temporal sequence is important, as it is particularly for policy gradient models). I guess the best way to integrate this is to introduce a new `Agent` subclass, something like `ParallelBatchAgent`, which handles this parallelism of timestep sequences appropriately. If you start doing this, let us know how it goes, and we could probably then integrate this new class at some point. 👍

**Comment by bigtreeliujie** [comment]
I am going to do the same job too. In my project, due to the real environment,  each agent runs at a very slow speed (3 step/s). As a result, I have to simultaneously run many agent (may be in different threads) to accelerate  the speed of observation generation, and train the model in synced mode with all the observation from different agents.  So I need something like `ParallelAgent`. However, as @AlexKuhnle  says, on-policy (BatchAgent)  and off-policy (MemoryAgent) are very different, which make the things even worse.

**Comment by AlexKuhnle** [comment]
The new version in dev branch supports basic batched `act()` handling now, see [here](https://github.com/reinforceio/tensorforce/blob/dev/tensorforce/models/model.py#L600).

**Comment by michaelschaarschmidt** [comment]
Seems like this can be closed now.
