### ISSUE TITLE
Enable non-square kernels for conv2d in layered_network_builder

### ISSUE THREAD

**Issue by tms1337** [reinforceio/tensorforce#151]
For instance (3, 1) kernels are not available in layered_nework_builder since it automatically assumes the size to be (window, window) which is 3 by default, so it is possible only to pass integer as a paramter, not tuple.

I needed this for one of the projects of my own. I tried searching but did not find similar issue open. I did not contribute to this repo earlier and I would be willing to do this feature since it is fairly simple and I would like to get familiar with the development process.

What are your thoughts on this?

**Comment by michaelschaarschmidt** [comment]
Hi, 

contributions are very welcome. Just as a heads-up, we are rolling out a new major release in the coming 1-2 weeks which will change the layer architectures - we cannot merge PRs until then

**Comment by AlexKuhnle** [comment]
We are not focussing on layer implementations very much, hence only the basic inventory we currently have. So contributions here are particularly welcome, there is lots of room for extensions... :-)  I think this specific extension could be integrated into the existing conv layer, just handling the alternative that window is a tuple/list instead of an int, what do you think? Also, as @michaelschaarschmidt said, the merge will have to wait 1-2 weeks.

**Comment by tms1337** [comment]
Yes it is just couple of lines that handle the tuple case. I will submit PR sometime soon then and then we can merge it when the major release is rolled out.

**Comment by AlexKuhnle** [comment]
Done.
