### ISSUE TITLE
Not possible to create custom TensorFlow network in #dev?

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#173]
#master had a handy feature where you can define your own network directly in TensorFlow, rather than using `layered_network_builder` (see [test_tutorial_code](https://github.com/reinforceio/tensorforce/blob/abfa09b08f3f49d81b081d84fa422190c3147b8b/tensorforce/tests/test_tutorial_code.py#L229)). I'm trying a use-case very similar to `test_tutorial_code` where I'd like to add part of the input downstream in the denses, after the convs.

From what I gather in #dev, the new custom-net approach is to subclass `LayerBasedNetwork` or `LayeredNetwork` (rather than defining a function per #master) and override `tf_apply()`. I tried such [here](https://gist.github.com/lefnire/304ed8fb75e1c7ba09ab30727ae22ed7). The problem is that the models call [Network.from_spec](https://github.com/reinforceio/tensorforce/blob/abfa09b08f3f49d81b081d84fa422190c3147b8b/tensorforce/models/q_model.py#L37), which explicitly assigns the subclass used to [LayeredNetwork](https://github.com/reinforceio/tensorforce/blob/abfa09b08f3f49d81b081d84fa422190c3147b8b/tensorforce/core/networks/network.py#L132). I can't think of how to infuse flexibility here, thoughts? Incidentally [this](https://github.com/lefnire/tensorforce/commit/913da64aabc979b4168c3f4a69ac92b2fe98906f) is my current work-around.

**Comment by AlexKuhnle** [comment]
Yes, that's right, because now networks (and layers) provide functions for retrieving their variables or regularization losses, they are classes instead of just functions (the function corresponding essentially to the implementation of `tf_apply`). the problem is, i think, that the `network` config entry doesn't exist anymore, and instead a separate `network_spec` argument is passed to the agent, and your code should work fine apart from that, i think. if you compare for instance with the test method [here](https://github.com/reinforceio/tensorforce/blob/dev/tensorforce/tests/base_agent_test.py#L118), which just passes the class (the class, not an instance) as argument for `network_spec`, that's essentially the same.

**Comment by AlexKuhnle** [comment]
Hmm, not sure whether this helps / solves all the problems, but let me know if there are problems.

**Comment by lefnire** [comment]
Thanks for the code reference, I'll play with that as a template in coming days & if still blocked will re-open

**Comment by lefnire** [comment]
Worked perfect. Trying to subclass `LayeredNetwork`, which expects a `layers_spec` arg was tripping me up (I wanted that `layers_spec` `list(dict)` abstraction y'all got going on, but w/ my own class) till I realized I should be subclassing `LayerBasedNetwork` instead. For anyone who does want said abstraction:

```python
def custom_net(layers_spec):
    class CustomNet(LayeredNetwork):
        def __init__(self, **kwargs):
            super(CustomNet, self).__init__(layers_spec, **kwargs)

        def tf_apply(self, x, internals=(), return_internals=False): ...

    return CustomNet

...
network_spec = custom_net([{'type':'dense'}])
```

Thanks again!
