### ISSUE TITLE
Network Structure for multiple inputs

### ISSUE THREAD

**Issue by etardis** [reinforceio/tensorforce#202]
Are there any network structure examples for Multimodal Inputs?  I have the structure for the State shown here:

https://github.com/reinforceio/tensorforce/issues/201

When I use a simple network like this:

    * Network as list of layers
    network_spec = [
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dense', size=32, activation='tanh'),
        dict(type='dueling', size=2, activation='none')
    ]

I get this error:
"Layered network must have only 1 input, but 2 given."

How do I generate a network to handle multiple inputs?

**Comment by AlexKuhnle** [comment]
Hi @etardis,

There is an example in our [introduction blogpost](https://reinforce.io/blog/introduction-to-tensorforce/) under "Neural network configuration". However, it's not possible to use the simplified network spec format, since they (currently) only work for layered networks (hence single input, single output).

Hope that helps!
