### ISSUE TITLE
Possible issue with Distribution_model entropy_regularization

### ISSUE THREAD

**Issue by Mazecreator** [reinforceio/tensorforce#224]
I am working on understanding the API and have bumped into an issue with setting "entropy_regularization" for a DQN test network I have setup.  Maybe this isn't valid for a DQN, but the regularization is actually making the loss go negative.  This appears to be due to the "entropy" value 
set here: https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/distribution_model.py#L187.

I plotted this value as returned and it is negative where I usually think of the cost as a positive number:
<img width="1926" alt="screenshot 2017-11-09 17 50 30" src="https://user-images.githubusercontent.com/18412448/32633924-6edc1a60-c577-11e7-86f0-8985ff761e70.png">

Here you can see my total-loss around 40K dipping below 0.00 line.
<img width="1926" alt="screenshot 2017-11-09 17 50 14" src="https://user-images.githubusercontent.com/18412448/32633951-89b76c22-c577-11e7-95ac-f519fc921599.png">

PS. I am chasing an issue of implementing L1/L2 loss in the DQN model as well hopefully I fill find this answer myself.

**Comment by Mazecreator** [comment]
Found the issue with the L1/L2 loss, it was in the Layer.py file:
https://github.com/reinforceio/tensorforce/pull/226

**Comment by AlexKuhnle** [comment]
Hi @Mazecreator, the loss is not necessarily a positive number, but it *is* a number that is supposed to be minimized. Now consider entropy regularization: We want to *punish* the model for being too certain about its actions, hence we want to encourage an *increase* in entropy. Since we minimize the loss, the increase is reflected by the number being negated. Hope that makes sense.
