### ISSUE TITLE
Add example use multi-layer Lstm

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#259]
I saw in https://github.com/reinforceio/tensorforce/commit/3021890d8efbd515d4fcf3a54bcfbcc79e5ba010 the new `Lstm` class's [comment](https://github.com/reinforceio/tensorforce/commit/3021890d8efbd515d4fcf3a54bcfbcc79e5ba010#diff-9d6635f99b67ca459d8cd019de727343R974) on stacking. Does this mean `Lstm` should be used for multi-layer rather than `InternalLstm`?  Rather: which class to use if we want multi-LSTM? 

* `[{'type':'internal_lstm', 'size':32}, {'type':'internal_lstm', 'size':32}` works
* `[{'type':'lstm', 'size':32}, {'type':'lstm', 'size':32}` gives `tensorforce.exception.TensorForceError: Invalid input rank for lstm layer: 2, must be 3.`

Creating an issue instead of asking in Gittr: if y'all get the chance, would be nice to add/modify an example or test to use multi-LSTM which can be followed in case of updates.

**Comment by AlexKuhnle** [comment]
First, the difference between the new `Lstm` and the old `Lstm` / new `InternalLstm`: The new LSTM is basically supposed to handle text or text-like symbol sequences as input, as compared to the Internal-LSTM, which processes a sequence across timesteps and hence at each moment only applies a single LSTM-Cell call.

The new LSTM per default returns the final hidden state (as often done in NLP), however, if one wants to apply multiple LSTM layer, one wants to use the output embeddings of the previous LSTM layer as input to the next LSTM layer (hence for all but the last `return_final_state=False`). The old Internal-LSTM can be stacked without problems, since it only does one step per timestep, not a sequence of steps.

Does that answer the question?

**Comment by lefnire** [comment]
Wonderful answer, thanks!
