### ISSUE TITLE
Large drop in performance when updating from 0.3.2 -> 0.3.5 (DQN,DDQN,PPO,TRPO)

### ISSUE THREAD

**Issue by SimonIgnat** [reinforceio/tensorforce#327]
Hi,

Firstly, thanks for such a great project! I understand that it's still in its alpha stage and therefore goes through a lot of changes. Guessing that it's the reason behind my problems.

I'm currently working on my master thesis and have been experimenting with a self written environment for tensorforce. Up until now I've worked with DQN, DDQN, PPO and TRPO with good and stable results. Today I decided to upgrade tensorforce so that I could work with some of the new features.

However, once upgraded (to 0.3.5) I noticed that none of the tuned agents, that worked good on 0.3.2, have the ability to learn anymore. The only thing that has changes is the syntax for initializing the agents, all the hyperparameters and settings are the same. 

Anyone have a clue what the reason behind this could be? I can always go back to 0.3.2 and have agents working again, but it would be nice to know what the reason might be (and maybe help you guys if it's caused by something else).  Since I'm doing it for my thesis my biggest concern is to have algorithms that are as close to theory as possible.

Best wishes,
Simon

**Comment by michaelschaarschmidt** [comment]
Hey,

unfortunately in 0.3.5, which is sort of an intermediate release towards moving everything fully into the computation graph, we uncovered some inconsistencies and performance problems along the way. Many of these have been identified and fixed in the new branch (on github) - the memory branch. The memory branch will complete the in-graph move and should improve performance, also fixing bugs that were present in 0.3.2. 

The branch is not completed and merging may take another 2-3 weeks, but you could try if it improves performance for you. It unfortunately brings some breaking API changes because it enables things such as updating based on the number of episodes instead of the number of time steps. Since some features in the branch are still being completed, these changes are not fully documented yet but you can come and join the chat to ask about any changes. Once that branch has been merged, we will fully focus on benchmark performance.

**Comment by SimonIgnat** [comment]
Thanks for the fast and well explained answer, really appreciate it!

I will try to use the new branch and gladly join the chat if I face any difficulties or find any problems. 

/Simon

**Comment by AlexKuhnle** [comment]
Have you tried / could you try the 'memory' branch in the most recent version and check whether you encounter the similarly inferior performance? There were some potentially relevant issues fixed recently...
