### ISSUE TITLE
How to preload weights for DQN agens

### ISSUE THREAD

**Issue by maximtzh1000** [reinforceio/tensorforce#357]
Let's say I have trained a Feed Forward supervised model with tensorflow. Is there a good way to preload the weights from that Feed Forward model for DQN model's network?

**Comment by michaelschaarschmidt** [comment]
Hi,

we currently only full standard model saving and loading. This would not work in your case since the DQN model needs other variables which are presumably not part of the feed forward model you want to load. 

Partial restoration is possible in general I think:
https://stackoverflow.com/questions/42217320/restore-variables-that-are-a-subset-of-new-model-in-tensorflow 
if you want to build functionality like this into the model (just load network weights), that would be very welcome as a PR

**Comment by michaelschaarschmidt** [comment]
Proposal from another user here: https://github.com/reinforceio/tensorforce/issues/363,
will close this and discussion can be in that issue.
