### ISSUE TITLE
Problem with Memory

### ISSUE THREAD

**Issue by SestoAle** [reinforceio/tensorforce#512]
Hi,

I'm a newbie to Deep RL and tensorforce and I'm trying to understand all the aspects of the algorithms.

I'm using the PPO agent right now but I have some doubts regarding the Update Method and Memory.
From what I understood, the update method sets the frequency of the back propagation of the net, so if I have:
```
update_mode=dict(
        unit='episodes',
        # 10 episodes per update
        batch_size=10,
        # Every 10 episodes
        frequency=10
    )
```
each 10 episodes, the weights of the net will be updated using the steps taken in the previous 10 episodes.
But what is the Memory component? The PPO default is: 
```
memory=dict(
        type='latest',
        include_next_states=False,
        capacity=1000*batch_size
    ),
```
but whats does it mean?

**Comment by AlexKuhnle** [comment]
Hey @SestoAle, the `latest` memory type just stores the most recent timesteps and "replays" them, not in a random order, but starting from the "latest" episode(/timestep). The capacity of this memory should hence be around `max_timesteps` * `num_episodes`. The memory type `replay`, in contrast, randomly replays from all experiences, hence makes sense to choose a larger capacity (that's essentially what is known from the classic DQN algorithm). I hope that helps, otherwise feel free to ask more!

**Comment by SestoAle** [comment]
So, in the case above, every 10 episodes the agent will update the weights of the net: to update these weights, it replays the latest 10000 (1000*10) steps. Instead, with `replay` type it samples 10000 steps from all experiences.
Is that right?

And, if the agent take less then 10000 steps in 10 episodes, it will use the experience stored the pas tepisodes or it use only the experiences stored in the last 10 episodes?

**Comment by AlexKuhnle** [comment]
Almost correct. In the above case, it will replay the 10 latest episodes (10*1000 guarantees that 10 full episodes of max length 1000 actually fit the memory, but depending on terminals it may contain older ones as well, but these have been used already and won't be another time). Similarly, in the case of `replay` it will randomly sample 10 episodes from the set of available episodes in the memory. Changing `mode` to `timestep` in `update_mode` does the same on a timestep-level.

**Comment by AlexKuhnle** [comment]
If a max number of timesteps is not known, the capacity has to be chosen more approximately. If the memory actually contains less than the required e.g. 10 episodes, either less episodes will be replayed or some will be replayed twice, can't quite remember, would have to check.

**Comment by AlexKuhnle** [comment]
The first part about the memories sounds right.

`batched_observe` is purely for computation performance reasons and means that internal `model.observe` is not called after every step, but buffered for `batched_capacity` timesteps (or at the end of an episode). This shouldn't affect actual task performance.

`distribution` is likely nothing to modify, but it generally allows to customize the distributions used to sample actions (custom implementation of `Distribution`). Default is Bernoulli for binary, Categorical for discrete, Gaussian for continuous, and Beta for bounded continuous actions.

It should be possible to set exploration for PPO agents, what happens if you do?

**Comment by SestoAle** [comment]
I'm sorry I was making messing with exploration, now it works!

So for now I have no more doubts, thank you for all the answers, you've been very kind!

**Comment by AlexKuhnle** [comment]
No problem. :-)

**Comment by SestoAle** [comment]
I'm sorry to bother you again, but I need another confirmation:

if i put

`update_mode=dict(
        unit='timesteps',
        batch_size=32,
        frequency=128
    ),`

it means that the net will update every 128 steps, using always 128 steps but with batches of 32 steps, or it will update every 128 steps using only 32 steps?

**Comment by AlexKuhnle** [comment]
The latter, so it will update every 128 steps based on one batch of 32 steps, so this setting probably doesn't make sense unless maybe one uses a "specialized" memory type, like prioritized replay.

**Comment by SestoAle** [comment]
I'm really sorry to bother you again, you were very kind so, if I can, I will ask you all the stupid questions that i have about tensorforce (I'm making a master thesis about reinforcement learning, and I can't understand the docs so well).

Is there any simple way to print a net summary, like all the layers and all of their input/output shapes?

**Comment by AlexKuhnle** [comment]
The most succinct format is probably the config you pass on to the agent, shapes shouldn't be difficult to infer from it. Another way is to inspect the TensorBoard graph summary, it contains all shapes but also the full computation graph which contains multiple calls to the network.

**Comment by SestoAle** [comment]
I have some more questions about CNNs:

Is it possible to print the output of an intermediate layer without using tensordboard? (I have some difficulties to understand how tensorboard works)

Is it possible to create a CNN with two branches, one that outputs the actions and one that outputs some custom feature? (Like the structure created in this article [https://arxiv.org/pdf/1609.05521.pdf](https://arxiv.org/pdf/1609.05521.pdf))

**Comment by AlexKuhnle** [comment]
Hey @SestoAle , mind switching this conversation to Gitter? You can message me there...
