### ISSUE TITLE
Configuration does not complain about extra parameters

### ISSUE THREAD

**Issue by befelix** [reinforceio/tensorforce#68]
Following up on the discussion on gitter so this doesn't get lost:

Right now if I misspell a parameter in the `Configuration` the library silently uses the default parameter instead. This can lead to annoying bugs.

**Comment by krfricke** [comment]
As discussed in Gitter, we decided to use the `Configuration` object during an earlier stage to have flexibility in combining different agents and models. Since that is not the case anymore (each agent has its own specific model) it might make sense to pass configuration parameters directly to the constructor of the agent, hence providing better readability and letting python raise errors when unexpected parameters are passed.

To avoid conflicts with #70, we could introduce an `Agent.create_model()` method as well as a static `Agent.with_model(model)`. The former would call `self.model = self.__class__.model(config)` if no model is provided, while the latter would create a new agent object with an existing model.

We'll discuss these changes shortly and will fix the issue asap.

**Comment by AlexKuhnle** [comment]
The `Configuration` object now keeps track of which values were accessed, and the `Agent` reports a warning containing the values that were not accessed by the end of the constructor.
