### ISSUE TITLE
Allow passing of a Model to an Agent

### ISSUE THREAD

**Issue by Islandman93** [reinforceio/tensorforce#70]
Currently agents are hardcoded to which models they use and the models are created in the agent.py __init__. This creates a 1 to 1 mapping that doesn't allow reuse of the agent class if a new model is created that follows the same interface as an existing model. 

Additionally, having this functionality should allow for easy multithreading capabilities since many agents could be created with the same shared model.

**Comment by krfricke** [comment]
If I understand correctly, this issue is not about combining agents with different models on the class level (such as the VPGAgent with a TRPOModel or alike), but about the possibility to hook specific model *instances* to agent instances. If that's the case, we can provide such functionality with the proposed update in #68, which we will discuss shortly.

**Comment by krfricke** [comment]
We decided to add a `model` parameter to the agent constructor, enabling passing of model instances.
